SELECT FIRST_HALF.FLAVOR FROM FIRST_HALF
    INNER JOIN ICECREAM_INFO
    ON ICECREAM_INFO.FLAVOR = FIRST_HALF.FLAVOR
WHERE ICECREAM_INFO.INGREDIENT_TYPE = 'fruit_based' AND FIRST_HALF.TOTAL_ORDER > 3000
ORDER BY FIRST_HALF.TOTAL_ORDER DESC;